### ISSUE TITLE
Can't find nuvoton driver.

### ISSUE THREAD

**Issue by junknet** [ehabhussein/AutoGadgetFS#4]
Only find these drivers:
Linux 5.12.14-arch1-1 xhci-hcd
None
Linux 5.12.14-arch1-1 xhci-hcd
Linux 5.12.14-arch1-1 xhci-hcd
Azurewave
Linux 5.12.14-arch1-1 xhci-hcd

**Comment by ehabhussein** [comment]
did you eject the device from the system before using it in agfs ?

**Comment by junknet** [comment]
Excuse me, but I'm a beginner.
I have no connection to the device.
Actually, I want to use the  raspberry zero emulated as a USB device  to fuzz a target (a embedded device).I don't know how to make it work.I'd appreciate it if you could give me some help.

> did you eject the device from the system before using it in agfs ?
